// TODO: Include packages needed for this application
const inquirer = require('inquirer');
const fs = require('fs');
// const { writeFile } = require('fs').promises;
const generateMarkdown = require('./utils/generateMarkdown');

function getLicense(value) {
    if (value === "Boost") {
        return "[![License](https://img.shields.io/badge/License-Boost%201.0-lightblue.svg)](https://www.boost.org/LICENSE_1_0.txt)";
    } else if (value === "Apache") {
        return "[![License](https://img.shields.io/badge/License-Apache%202.0-blue.svg)](https://opensource.org/license/apache2-0-php/)";
    } else if (value === "GNU AGPLv3") {
        return "[![License: AGPL v3](https://img.shields.io/badge/License-AGPL%20v3-blue.svg)](https://www.gnu.org/licenses/agpl-3.0)";
    } else if (value === "GNU GPLv3") {
        return "[![License: GPL v3](https://img.shields.io/badge/License-GPLv3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0)";
    } else if (value === "GNU LGPLv3") {
        return "[![License: LGPL v3](https://img.shields.io/badge/License-LGPL%20v3-blue.svg)](https://www.gnu.org/licenses/lgpl-3.0)";
    } else if (value === "MIT") {
        return "[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)";
    } else if (value === "MPL") {
        return "[![License: MPL 2.0](https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg)](https://opensource.org/licenses/MPL-2.0)";
    }
}

function licenseNotice(value) {
    if (value === "Boost") {
        return `Boost Software License - Version 1.0 - August 17th, 2003

        Permission is hereby granted, free of charge, to any person or organization
        obtaining a copy of the software and accompanying documentation covered by
        this license (the "Software") to use, reproduce, display, distribute,
        execute, and transmit the Software, and to prepare derivative works of the
        Software, and to permit third-parties to whom the Software is furnished to
        do so, all subject to the following:
        
        The copyright notices in the Software and this entire statement, including
        the above license grant, this restriction and the following disclaimer,
        must be included in all copies of the Software, in whole or in part, and
        all derivative works of the Software, unless such copies or derivative
        works are solely in the form of machine-executable object code generated by
        a source language processor.
        
        THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
        IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
        FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
        SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
        FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
        ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
        DEALINGS IN THE SOFTWARE.`;
    } else if (value === "Apache") {
        return `Copyright 2004 Apache Software Foundation

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at
     
          http://www.apache.org/licenses/LICENSE-2.0
     
        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.`;
    } else if (value === "GNU AGPLv3") {
        return `2007 Free Software Foundation, Inc

        This program is free software: you can redistribute it and/or modify
        it under the terms of the GNU Affero General Public License as
        published by the Free Software Foundation, either version 3 of the
        License, or (at your option) any later version.
    
        This program is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU Affero General Public License for more details.
    
        For a copy of the GNU Affero General Public License, see <https://www.gnu.org/licenses/>.`;
    } else if (value === "GNU GPLv3") {
        return  `2007 Free Software Foundation, Inc
    
        This program is free software: you can redistribute it and/or modify
        it under the terms of the GNU General Public License as published by
        the Free Software Foundation, either version 3 of the License, or
        (at your option) any later version.

        This program is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU General Public License for more details.
        
        For a copy of the GNU Affero General Public License, see <https://www.gnu.org/licenses/>.`;
    } else if (value === "GNU LGPLv3") {
        return `2007 Free Software Foundation, Inc

        This program is free software: you can redistribute it and/or modify
        it under the terms of the GNU General Public License as published by
        the Free Software Foundation, either version 3 of the License, or
        (at your option) any later version.
    
        This program is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU General Public License for more details.
    
        For a copy of the GNU Affero General Public License, see <https://www.gnu.org/licenses/>.`;
    } else if (value === "MIT") {
        return `Copyright Unknown

        Permission is hereby granted, free of charge, to any person 
        obtaining a copy of this software and associated documentation 
        files (the “Software”), to deal in the Software without restriction, 
        including without limitation the rights to use, copy, modify, 
        merge, publish, distribute, sublicense, and/or sell copies of 
        the Software, and to permit persons to whom the Software is 
        furnished to do so.
        
        THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, 
        EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES 
        OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
        NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
        HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
        WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
        FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR 
        OTHER DEALINGS IN THE SOFTWARE.`
    } else if (value === "MPL") {
        return `This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. 

        If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.`
    }
}
// TODO: Create an array of questions for user input


function githubLink(value) {
    return `https://github.com/${value}`
}

function userEmail(value) {
  return `<a href="mailto:${value}">${value}</a>`
}

const questions = [
          {
              type: 'input',
              name: 'projectName',
              message: 'What is the name of the project?'
          },
          {
              type: 'input',
              name: 'repo',
              message: 'URL of Github repository:'
          },
          {
              type: 'list',
              name: 'license',
              message: 'What license do you want?',
              choices: ['none', 'Boost', 'Apache', 'MIT', 'MPL', 'GNU AGPLv3', 'GNU GPLv3', 'GNU LGPLv3',],
          },
          {
              type: 'input',
              name: 'description',
              message: 'Please give a brief description of your project, like - What was your motivation? - Why did you build this project? - What problem does it solve? - What did you learn?:'
          },
          {
              type: 'input',
              name: 'install',
              message: 'Provide a step-by-step description of how to get the development environment running:'
          },
          {
              type: 'input',
              name: 'usage',
              message: 'What dependencies are you using?'
          },
          {
              type: 'input',
              name: 'tests',
              message: 'What commands were used to test this app?'
          },
          {
              type: 'input',
              name: 'credits',
              message: 'List collaborators:'
          },
          {
              type: 'input',
              name: 'github',
              message: 'Enter GitHub username:'
          },
          {
              type: 'input',
              name: 'email',
              message: 'Enter email:'
          },
        ];

function writeToFile(fileName, data) {
    fs.writeFile(fileName, generateMarkdown(data), function (err) {
        if (err) {
            return console.log(err, 'error writing file');
        }
    });
}

function init() {
    inquirer.prompt(questions).then(
        (data) => {
        console.log(JSON.stringify(data, null, " "));
        data.getLicense = getLicense(data.license);
        data.licenseNotice = licenseNotice(data.license);
        data.githubLink= githubLink(data.github);
        data.userEmail= userEmail(data.email);
        writeToFile("ExampleREADME.md", data);
    });
}


  init();